const pageData={
 home:{title:'🏠 HOME',html:`<div class="grid"><div class="profile"><h2>👤 STUDENT</h2><p>Name: Nimra</p><p>Roll No: 12345</p><p>Semester: 4</p></div><div class="tiles"><div class="tile blue" data-tab="courses">📚<br>Courses</div><div class="tile green" data-tab="fees">💵<br>Fees</div><div class="tile purple" data-tab="results">📊<br>Result</div><div class="tile orange" data-tab="attendance">📅<br>Attendance</div><div class="tile red" data-tab="notifications">🔔<br>Notice</div><div class="tile pink" data-tab="events">🎫<br>Event</div><div class="tile blue" data-tab="library">📖<br>Library</div><div class="tile green" data-tab="complaints">✉<br>Complaint</div><div class="tile purple" data-tab="profile">👤<br>Profile</div><div class="tile orange" data-tab="settings">⚙<br>Settings</div></div><div class="sidebox"><h2>UPCOMING</h2><ul><li>Assignment Due - 22 Sep</li><li>Midterm Exam - 25 Sep</li><li>Fee Submission - 25 Sep</li><li>Career Fair - 30 Sep</li></ul><h2>RECENT NOTICES</h2><ul><li>Semester schedule updated</li><li>Fee deadline extended</li><li>New library books available</li></ul></div></div>`},
 profile:{title:'👤 PROFILE',html:`<div class="panel-title"><h2>Student Profile</h2></div><p><b>Name:</b> Nimra</p><p><b>Roll No:</b> 12345</p><p><b>Program:</b> Software Engineering</p><p><b>Semester:</b> 4</p><p><b>Email:</b> student@university.edu</p><button class="action-btn" onclick="openModal('Edit Profile','<form class=mini-form><label>Full Name</label><input value=Nimra><label>Email</label><input value=student@university.edu><button class=action-btn type=button onclick=closeModal()>Save Changes</button></form>')">Edit Profile</button>`},
 courses:{title:'📚 COURSES',html:`<div class="panel-title"><h2>My Courses</h2></div><table class="bad-table"><tr><th>Course</th><th>Teacher</th><th>Credits</th><th>Status</th></tr><tr><td>Database Systems</td><td>Dr. Ahmed</td><td>3</td><td>Active</td></tr><tr><td>Computer Networks</td><td>Ms. Sara</td><td>3</td><td>Active</td></tr><tr><td>HCI & CG</td><td>Mr. Ali</td><td>3</td><td>Active</td></tr><tr><td>Software Engineering</td><td>Dr. Khan</td><td>3</td><td>Active</td></tr></table>`},
 fees:{title:'💰 FEES',html:`<div class="panel-title"><h2>Fee Information</h2></div><p><b>Current Status:</b> Paid</p><p><b>Semester Fee:</b> Rs. 45,000</p><p><b>Last Payment:</b> 05 Sep 2026</p><button class="action-btn" onclick="openModal('Online Fee Payment','<p>Your current fee balance is <b>Rs. 0</b>.</p><button class=action-btn onclick=closeModal()>Close</button>')">Open Payment</button>`},
 results:{title:'📊 RESULTS',html:`<div class="panel-title"><h2>Semester Results</h2></div><table class="bad-table"><tr><th>Course</th><th>Marks</th><th>Grade</th></tr><tr><td>Database Systems</td><td>86</td><td>A</td></tr><tr><td>Computer Networks</td><td>82</td><td>A-</td></tr><tr><td>HCI & CG</td><td>90</td><td>A+</td></tr><tr><td>Software Engineering</td><td>84</td><td>A-</td></tr></table><h3>Current GPA: 3.45</h3>`},
 attendance:{title:'📅 ATTENDANCE',html:`<div class="panel-title"><h2>Attendance</h2></div><table class="bad-table"><tr><th>Course</th><th>Present</th><th>Total</th><th>Percentage</th></tr><tr><td>Database Systems</td><td>18</td><td>20</td><td>90%</td></tr><tr><td>Networks</td><td>17</td><td>20</td><td>85%</td></tr><tr><td>HCI & CG</td><td>19</td><td>20</td><td>95%</td></tr><tr><td>Software Engineering</td><td>19</td><td>20</td><td>95%</td></tr></table>`},
 library:{title:'📖 LIBRARY',html:`<div class="panel-title"><h2>Library</h2></div><p><b>Books issued:</b> 2</p><ul><li>Human Computer Interaction — Return: 05 Oct</li><li>Database Systems — Return: 10 Oct</li></ul><button class="action-btn" onclick="openModal('Library Search','<form class=mini-form><input placeholder=Search\u0020book><button type=button class=action-btn onclick=closeModal()>Search</button></form>')">Search Books</button>`},
 complaints:{title:'✉ COMPLAINTS',html:`<div class="panel-title"><h2>Submit a Complaint</h2></div><form class="mini-form" onsubmit="submitComplaint(event)"><label>Subject</label><input id="complaintSubject" required><label>Details</label><textarea id="complaintDetails" rows="5" required></textarea><button class="action-btn">Submit Complaint</button></form><div id="complaintMessage"></div>`},
 events:{title:'🎫 EVENTS & SCHEDULE',html:`<div class="panel-title"><h2>Upcoming Events</h2></div><ul><li>22 Sep — Database Systems Exam — Room 201</li><li>25 Sep — Assignment Submission — Networks</li><li>30 Sep — Career Fair — Main Auditorium</li><li>05 Oct — Sports Week</li></ul><button class="action-btn" onclick="openModal('Event Registration','<p>You selected Career Fair. Registration is open.</p><button class=action-btn onclick=closeModal()>Register</button>')">Register for Event</button>`},
 notifications:{title:'🔔 NOTIFICATIONS',html:`<div class="panel-title"><h2>Notifications</h2></div><ul><li>Semester schedule updated — 2 days ago</li><li>Fee deadline announced — 3 days ago</li><li>New library books available — 5 days ago</li><li>Sports week registration open — 1 week ago</li></ul>`},
 settings:{title:'⚙ SETTINGS',html:`<div class="panel-title"><h2>Settings</h2></div><form class="mini-form" onsubmit="saveSettings(event)"><label><input type="checkbox" checked> Email notifications</label><label><input type="checkbox" checked> Exam reminders</label><label>Theme <select><option>Bright</option><option>Default</option></select></label><button class="action-btn">Save Settings</button></form><div id="settingsMessage"></div>`}
};
function renderTab(tab){const data=pageData[tab]||pageData.home;const box=document.getElementById('dashboardContent');box.innerHTML=`<section class="content-panel"><h1>${data.title}</h1>${data.html}</section>`;document.querySelectorAll('.dashnav a').forEach(a=>a.classList.toggle('active',a.dataset.tab===tab));document.querySelectorAll('[data-tab]').forEach(el=>el.onclick=function(e){e.preventDefault();renderTab(this.dataset.tab)});window.scrollTo({top:0,behavior:'smooth'})}
function login(){const u=document.getElementById('username').value.trim();const p=document.getElementById('password').value.trim();const m=document.getElementById('message');if(!u||!p){m.innerHTML='<p class="error">Please enter both username and password.</p>';return}if(document.getElementById('remember').checked)localStorage.setItem('portalUser',u);location.href='dashboard.html'}
function logout(){location.href='index.html'}
function registerUser(){openModal('Registration','<p>Registration is available for new students.</p><form class=mini-form><label>Name</label><input required><label>University Email</label><input type=email required><label>Password</label><input type=password required><button type=button class=action-btn onclick=closeModal()>Create Account</button></form>')}
function forgotPassword(){openModal('Reset Password','<p>Enter your university email and a reset instruction will be sent.</p><form class=mini-form><input type=email placeholder=student@university.edu required><button type=button class=action-btn onclick="openModal(\'Reset Request Sent\',\'<p>Please check your email for reset instructions.</p>\')">Send Reset Link</button></form>')}
function openModal(title,html){document.getElementById('modalContent').innerHTML=`<h2>${title}</h2>${html}`;document.getElementById('modal').classList.remove('hidden')}
function closeModal(){document.getElementById('modal').classList.add('hidden')}
function submitComplaint(e){e.preventDefault();document.getElementById('complaintMessage').innerHTML='<p><b>Complaint submitted successfully.</b> Reference: CMP-1024</p>';e.target.reset()}
function saveSettings(e){e.preventDefault();document.getElementById('settingsMessage').innerHTML='<p><b>Settings saved.</b></p>'}
document.addEventListener('click',e=>{const page=e.target.closest('[data-page]');if(page){e.preventDefault();const p=page.dataset.page;if(location.pathname.endsWith('dashboard.html'))renderTab(p);else if(p==='home')document.getElementById('loginSection').scrollIntoView({behavior:'smooth'});else openModal('Quick Link',`<p>${p.charAt(0).toUpperCase()+p.slice(1)} is available after login.</p><button class=action-btn onclick="location.href='dashboard.html'">Open Dashboard</button>`)}const modal=e.target.closest('[data-modal]');if(modal){e.preventDefault();const type=modal.dataset.modal;const map={about:['About','University Student Portal — HCI Experiment Version 1.'],help:['Help','Use the Quick Menu and dashboard tabs to access portal features.'],contact:['Contact','Email: info@university.edu<br>Phone: +92-123456789'],terms:['Terms','This demonstration portal is for academic HCI use.'],privacy:['Privacy','This demo does not collect real personal information.'],complaint:['Complaint Form','<form class=mini-form onsubmit="event.preventDefault();closeModal();alert(\'Complaint submitted.\')"><input placeholder=Subject required><textarea placeholder=Details required></textarea><button class=action-btn>Submit</button></form>']};openModal(map[type][0],map[type][1])}});
if(location.pathname.endsWith('dashboard.html'))renderTab('home');
